# Generated by Django 4.2.1 on 2023-05-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='audio_path',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
