# Generated by Django 4.2.1 on 2023-05-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_request_audio_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Representative',
            new_name='Agent',
        ),
    ]
